# Generated by Django 4.2.1 on 2023-05-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_china', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/105/105544.png', max_length=500, upload_to='profile_pictures/'),
        ),
    ]
