# Generated by Django 4.2.1 on 2023-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_china', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='progreso_historia',
            field=models.JSONField(default={'arquitectura': 0, 'datos': 0, 'han': 0, 'qin': 0, 'shang': 0, 'xia': 0, 'zhou': 0}),
        ),
    ]
