# Generated by Django 4.2.1 on 2023-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_china', '0004_customuser_progreso_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='progreso_contribuciones',
            field=models.JSONField(default={'acupuntura': 0, 'brujula': 0, 'datos_contribuciones': 0, 'imprenta': 0, 'papel': 0, 'polvora': 0}),
        ),
        migrations.AddField(
            model_name='customuser',
            name='progreso_cultura',
            field=models.JSONField(default={'artesanias': 0, 'creencias': 0, 'datos_cultura': 0, 'festividades': 0, 'tradiciones': 0, 'vestimenta': 0}),
        ),
    ]
