/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

/**
 * Componente del modelo de la dinastía.
 *
 * Este componente representa un modelo 3D de un guerrero chino de una dinastía.
 * Utiliza el paquete @react-three/drei para cargar y renderizar el modelo.
 *
 * @param {object} props - Props adicionales para el componente.
 * @returns {JSX.Element} - El componente del modelo de la dinastía.
 *
 */

export function Modelo_dinastia(props) {
  // Carga el modelo y los materiales utilizando la función useGLTF de @react-three/drei
  const { nodes, materials } = useGLTF("/static/guerrero_chino.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChnArcher_001.geometry}
        material={nodes.ChnArcher_001.material}
      />
    </group>
  );
}


// Precarga el modelo para mejorar el rendimiento
useGLTF.preload("/static/guerrero_chino.glb");
